CREATE TABLE JSONSTORE
(
  OBJECT_ID Integer NOT NULL,
  PROPERTY_PATH VARCHAR (200) NOT NULL,
  PROPERTY_TYPE VARCHAR (4) NOT NULL,
  PROPERTY_VALUE VARCHAR (300),
  CONSTRAINT jsonstore_pk PRIMARY KEY (OBJECT_ID,PROPERTY_PATH)
)