CREATE TABLE PERIODIC_TASK_STATUS
(
  TASK_ID Varchar(24) NOT NULL PRIMARY KEY,
  TASK_STATUS varchar(10) NOT NULL check(TASK_STATUS = 'IN_ERROR' OR TASK_STATUS = 'RUNNING'),
  ERROR varchar(100),
  LAST_EXECUTION TIMESTAMP
);

CREATE TABLE PURCHASE_UPLOAD_LOG
(
  PURCHASE_ID Varchar(24) NOT NULL PRIMARY KEY,
  UPLOAD_STATUS varchar(10) NOT NULL check(UPLOAD_STATUS = 'FAILED' OR UPLOAD_STATUS = 'DONE' OR UPLOAD_STATUS = 'RETRYING'),
  UPLOAD_ERROR varchar(100),
  CREATED TIMESTAMP,
  LAST_UPLOAD_ATTEMPT TIMESTAMP
);