CREATE TABLE HENTS
(
  HENTID Integer NOT NULL PRIMARY KEY autoincrement,
  ALIAS Varchar(24) NOT NULL,
  HENTNAME Varchar(64) NOT NULL,
  ZIP Varchar(10),
  CITY Varchar(48),
  STREET Varchar(48),
  POBOX Varchar(10),
  NIP Char(10),
  HENTNO Char(14) NOT NULL UNIQUE,
  WETNO Char(8),
  PHONE Varchar(12),
  PLATE Varchar(16),
  HENTTYPE char NOT NULL check(HENTTYPE = 'C' OR HENTTYPE = 'I'),
  EXTRAS Varchar(255),
  ACCOUNTNO Char(28),
  BANKNAME Varchar(50),
  PESEL Char(11),
  REGON Varchar(14),
  IDNO Varchar(12),
  ISSUEPOST Varchar(50),
  ISSUEDATE Date,
  CELLPHONE Varchar(16),
  EMAIL Varchar(64),
  LATITUDE Numeric(15,12),
  LONGITUDE Numeric(15,12),
  WETLICENCENO Varchar(12)
);

CREATE TABLE CLASSES
(
  NAME Varchar(64),
  CODE Varchar(8) NOT NULL UNIQUE,
  CLASSID Integer NOT NULL  PRIMARY KEY AUTOINCREMENT,
  PREDEFSEX Integer CHECK(predefsex = -1 OR predefsex = 1 OR predefsex = 0),
  PRICEPERKG Number(15,5)
);

CREATE TABLE STOCKS
(
  NAME Varchar(64),
  CODE Varchar(8) NOT NULL UNIQUE,
  STOCKID Integer NOT NULL  PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE HERDS
(
  HERDNUMBER INT NOT NULL UNIQUE,
  HERDID Integer NOT NULL  PRIMARY KEY AUTOINCREMENT,
  ZIP Varchar(10),
  CITY Varchar(48),
  STREET Varchar(48),
  POBOX Varchar(10)
);

CREATE TABLE DEDUCTION_DEFINITIONS
(
  DEDUCTION_ID Integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  CODE Varchar(10) NOT NULL,
  FRACTION Numeric(15,5) NOT NULL,
  REASON Varchar(300) NOT NULL,
  ALWAYS INTEGER NOT NULL CHECK (ALWAYS = 0 OR ALWAYS = 1)
);

create table purchases
(
purchaseid INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
start DATE NOT NULL,
end DATE,
plateno VARCHAR(20),
state varchar(6) NOT NULL CHECK(state = 'OPEN' OR state = 'CLOSED' OR state = 'QUEUED' OR state = 'SENT'),
herdno INTEGER NOT NULL
);

CREATE TABLE INVOICES
(
  INVOICEID Integer NOT NULL PRIMARY  KEY AUTOINCREMENT,
  VATRATE Numeric(15,5),
  PAYWAY Char(1) NOT NULL CHECK(PAYWAY = '$' OR PAYWAY = '@'),
  CUSTOMNUMBER Varchar(15),
  PAYDUEDAYS Integer CHECK(PAYDUEDAYS >= 0),
  PURACHE INTEGER NOT NULL,
  INVOICEDT DATE,
  TRANSACTIONDT DATE,
  TRANSACTIONPLACE VARCHAR(48),
  INVOICETYPE CHAR(1) NOT NULL CHECK(INVOICETYPE = 'L' OR INVOICETYPE = 'V'),
  EXTRAS VARCHAR(255),

  CONSTRAINT  INVOICES_PURACHES_FK FOREIGN KEY (PURACHE) REFERENCES puraches(puracheid)

);

CREATE TABLE INVOICE_DEDUCTIONS
(
  INVOICEID Integer NOT NULL,
  CODE Varchar(10) NOT NULL,
  FRACTION Numeric(15,5) NOT NULL,
  REASON Varchar(300) NOT NULL,
  ENABLED INTEGER NOT NULL CHECK(ENABLED = 0 OR ENABLED = 1),
  CONSTRAINT  INVOICE_DEDUCTIONS_FK FOREIGN KEY (INVOICEID) REFERENCES invoice(INVOICEID)
);

CREATE TABLE INVOICE_HENTS
(
  INVOICEID Integer NOT NULL,
  HENTNAME Varchar(64) NOT NULL,
  ZIP Varchar(10),
  CITY Varchar(48),
  STREET Varchar(48),
  POBOX Varchar(10),
  NIP Char(10),
  HENTNO Char(14) NOT NULL,
  WETNO Char(8),
  PHONE Varchar(12),
  ACCOUNTNO Char(28),
  BANKNAME Varchar(50),
  PESEL Char(11),
  REGON Varchar(14),
  IDNO Varchar(12),
  ISSUEPOST Varchar(50),
  ISSUEDATE Date,
  CELLPHONE Varchar(16),
  EMAIL Varchar(64),
  WETLICENCENO Varchar(12),

  CONSTRAINT  INVOICE_HENTS_FK FOREIGN KEY (INVOICEID) REFERENCES invoice(INVOICEID)

);

CREATE TABLE COWS
(
  COWID Integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  EAN varchar(14) NOT NULL,
  SEX Integer CHECK(sex = -1 OR sex = 1 OR sex = 0),
  STOCK varchar(8),
  CLASS varchar(8) NOT NULL,
  WEIGHT Integer NOT NULL CHECK(weight > 0),
  PRICE Numeric(15,5) NOT NULL CHECK(price > 0),
  INVOICE INTEGER NOT NULL,
  LATITUDE Numeric(15,12),
  LONGITUDE Numeric(15,12),
  FIRSTOWNER Integer,
  PASSPORTNO varchar(14),
  PASSPORTISSUEDT Date,
  HEALTHCERTNO varchar(16),
  MOTHEREAN varchar(14),
  BIRTHPLACE varchar(32),
  BIRTHDT Date,
  TOTNETPRICE Numeric(15,5),
  TOTGROSSPRICE Numeric(15,5),
  PERKGNETPRICE Numeric(15,5),
  PERKGGROSSPRICE Numeric(15,5),

  CONSTRAINT COWS_INVOICES_FK FOREIGN KEY (invoice) REFERENCES invoices(invoiceid),
  CONSTRAINT COWS_HENTS_FK FOREIGN KEY (FIRSTOWNER) REFERENCES hents(hentid)
);


CREATE TABLE SETTINGS
(
  NAME varchar(30) NOT NULL,
  TYPE char(4) NOT NULL CHECK(TYPE = 'LONG' OR TYPE = 'STRN' OR TYPE = 'DATE' OR TYPE = 'BOOL' OR TYPE = 'DBL.' OR TYPE = 'INT.'),
  VALUE varchar(70),
  CONSTRAINT SETTINGS_PK PRIMARY KEY(NAME)

);

INSERT INTO SETTINGS(NAME,TYPE,VALUE) VALUES('COMPANY_NAME','STRN','Nazwa Firmy');
INSERT INTO SETTINGS(NAME,TYPE,VALUE) VALUES('COMPANY_STREET','STRN','Ulica');
INSERT INTO SETTINGS(NAME,TYPE,VALUE) VALUES('COMPANY_POBOX','STRN','Nr');
INSERT INTO SETTINGS(NAME,TYPE,VALUE) VALUES('COMPANY_CITY','STRN','Miasto');
INSERT INTO SETTINGS(NAME,TYPE,VALUE) VALUES('COMPANY_ZIP','STRN','Kod');
INSERT INTO SETTINGS(NAME,TYPE,VALUE) VALUES('COMPANY_FARMNO','STRN','PL000000000000');
INSERT INTO SETTINGS(NAME,TYPE,VALUE) VALUES('COMPANY_CELLPHONENO','STRN','000000000');
INSERT INTO SETTINGS(NAME,TYPE,VALUE) VALUES('COMPANY_PHONENO','STRN','000000000');
INSERT INTO SETTINGS(NAME,TYPE,VALUE) VALUES('COMPANY_EMAIL','STRN','company@company.com');
INSERT INTO SETTINGS(NAME,TYPE,VALUE) VALUES('COMPANY_NIP','STRN','0000000000');

CREATE TABLE DOCUMENT_PREFERENCES
(
  DOCCODE Varchar(20) NOT NULL,
  VISIBLE INT NOT NULL CHECK(VISIBLE = 1 OR VISIBLE = 0)
);

CREATE TABLE DOCUMENT_OPTIONS_PROFILE
(
  PROFILEID Integer NOT NULL PRIMARY  KEY AUTOINCREMENT,
  PROFILENAME Varchar(50) NOT NULL,
  DOCCODE Varchar(20) NOT NULL
);

CREATE TABLE DOCUMENT_OPTIONS
(
  PROFILEID Integer NOT NULL,
  OPTIONNAME Varchar(30) NOT NULL,
  PARTINDEX INTEGER NOT NULL,
  OPTIONVALUE Varchar(100),

  CONSTRAINT  DOCUMENT_OPTIONS_PK PRIMARY KEY (PROFILEID,OPTIONNAME),
  CONSTRAINT  OPTIONS_PROFILE_FK FOREIGN KEY (PROFILEID) REFERENCES OPTIONS_PROFILE(PROFILEID)
);

CREATE TABLE INVOICENO_TRANSACTION
(
  TRANSACTION_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  INVOICE_NO Integer NOT NULL,
  STATE char(1) NOT NULL CHECK(state = 'A' OR state = 'U' OR state = 'R')
);