CREATE TABLE STATEMENTS
(
  STATEMENT_ID Integer NOT NULL PRIMARY KEY AUTOINCREMENT,
  STATEMENT_CODE Varchar(10) NOT NULL,
  STATEMENT_TEXT Varchar(300) NOT NULL,
  ALWAYS INTEGER NOT NULL CHECK (ALWAYS = 0 OR ALWAYS = 1)

);
