apply plugin: 'com.android.library'

android {
    compileSdkVersion 35


    repositories {
        mavenCentral()
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/ASL2.0', 'META-INF/LICENSE', 'META-INF/NOTICE']
        }
    }


    defaultConfig {
        minSdkVersion 33
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.bk.print'
    lint {
        abortOnError false
        targetSdk 35
    }


}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':bkbands')
    implementation project(':bluetoothcommon')
    implementation 'com.couchbase.lite:couchbase-lite-android:4.0.3'
    implementation 'com.google.guava:guava:33.6.0-android'
    implementation("com.fasterxml.jackson.core:jackson-databind:2.21.3")
}

